"""update schemas

Revision ID: 027dbe8bdaa6
Revises: cd742bf89220
Create Date: 2026-07-05 15:14:50.731123
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '027dbe8bdaa6'
down_revision: Union[str, None] = 'cd742bf89220'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
