"""update schemas

Revision ID: cd742bf89220
Revises: 0002
Create Date: 2026-07-05 13:03:48.749770
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cd742bf89220'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
